name: Integracion continua con python

on:
  pull_request:
    branches: [ master ]

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8 
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --Count--Select = E9, F63, F7, F82--show-Source--Statistics
          # exit-zero trata todos los errores como advertencias. El editor de GitHub es 127 chars de ancho
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest